% /****************************************************************************
%  *
%  *    Copyright (C) 2024  Yevhenii Kovryzhenko. All rights reserved.
%  *
%  *    This program is free software: you can redistribute it and/or modify
%  *    it under the terms of the GNU Affero General Public License as published by
%  *    the Free Software Foundation, either version 3 of the License, or
%  *    (at your option) any later version.
%  *
%  *    This program is distributed in the hope that it will be useful,
%  *    but WITHOUT ANY WARRANTY; without even the implied warranty of
%  *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  *    GNU Affero General Public License Version 3 for more details.
%  *
%  *    You should have received a copy of the
%  *    GNU Affero General Public License Version 3
%  *    along with this program.  If not, see <https://www.gnu.org/licenses/>.
%  *
%  *    1. Redistributions of source code must retain the above copyright
%  *       notice, this list of conditions, and the following disclaimer.
%  *    2. Redistributions in binary form must reproduce the above copyright
%  *       notice, this list of conditions, and the following disclaimer in
%  *       the documentation and/or other materials provided with the
%  *       distribution.
%  *    3. No ownership or credit shall be claimed by anyone not mentioned in
%  *       the above copyright statement.
%  *    4. Any redistribution or public use of this software, in whole or in part,
%  *       whether standalone or as part of a different project, must remain
%  *       under the terms of the GNU Affero General Public License Version 3,
%  *       and all distributions in binary form must be accompanied by a copy of
%  *       the source code, as stated in the GNU Affero General Public License.
%  *
%  ****************************************************************************/

function Q_prime = get_Q_prime(T)
%get_Q_prime
%    Q_prime = get_Q_prime(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    05-Feb-2024 11:01:36

t2 = 1.0./T;
t9 = T.*(5.0./9.9e+1);
t10 = T./1.98e+2;
t3 = t2.^2;
t4 = t2.^3;
t6 = t2.^5;
t8 = t2.^7;
t11 = t2.*(1.0e+2./1.1e+1);
t12 = t2.*(8.0e+1./3.3e+1);
t13 = t2.*(1.9e+2./3.3e+1);
t14 = t2.*(3.2e+2./1.1e+1);
t5 = t3.^2;
t7 = t3.^3;
t15 = t4.*(4.2e+2./1.1e+1);
t16 = -t12;
t18 = t3.*(5.2e+2./3.3e+1);
t19 = t3.*(7.4e+2./3.3e+1);
t20 = t3.*1.218181818181818e+2;
t21 = t3.*2.218181818181818e+2;
t22 = t4.*7.018181818181818e+2;
t27 = t4.*9.018181818181818e+2;
t28 = t4.*1.476363636363636e+3;
t30 = t4.*2.036363636363636e+3;
t35 = t6.*1.695272727272727e+4;
t36 = t6.*4.011636363636364e+4;
t37 = t6.*4.235636363636364e+4;
t42 = t8.*1.649454545454545e+5;
t17 = -t15;
t23 = -t18;
t24 = -t19;
t25 = -t20;
t26 = -t21;
t29 = t5.*1.603636363636364e+3;
t31 = -t28;
t33 = t5.*7.916363636363636e+3;
t34 = t5.*9.036363636363636e+3;
t40 = -t35;
t41 = t7.*8.247272727272727e+4;
t44 = -t42;
t32 = -t29;
t38 = -t33;
t39 = -t34;
t43 = -t41;
Q_prime = sparse([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10],[1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,8,8,9,9,9,9,9,9,9,9,9,9,10,10,10,10,10,10,10,10,10,10],[t42,t41,t35,t29,t15,t44,t41,t40,t29,t17,t41,t37,t34,t27,t19,t43,t36,t38,t22,t23,t35,t34,t30,t21,t13,t40,t33,t31,t20,t16,t29,t27,t21,t14,2.6e+1./3.3e+1,t32,t22,t25,t11,-4.0./3.3e+1,t15,t19,t13,2.6e+1./3.3e+1,t9,t17,t18,t16,4.0./3.3e+1,t10,t44,t43,t40,t32,t17,t42,t43,t35,t32,t15,t41,t36,t33,t22,t18,t43,t37,t39,t27,t24,t40,t38,t31,t25,t16,t35,t39,t30,t26,t13,t29,t22,t20,t11,4.0./3.3e+1,t32,t27,t26,t14,-2.6e+1./3.3e+1,t17,t23,t16,-4.0./3.3e+1,t10,t15,t24,t13,-2.6e+1./3.3e+1,t9],10,10);
end