% /****************************************************************************
%  *
%  *    Copyright (C) 2024  Yevhenii Kovryzhenko. All rights reserved.
%  *
%  *    This program is free software: you can redistribute it and/or modify
%  *    it under the terms of the GNU Affero General Public License as published by
%  *    the Free Software Foundation, either version 3 of the License, or
%  *    (at your option) any later version.
%  *
%  *    This program is distributed in the hope that it will be useful,
%  *    but WITHOUT ANY WARRANTY; without even the implied warranty of
%  *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  *    GNU Affero General Public License Version 3 for more details.
%  *
%  *    You should have received a copy of the
%  *    GNU Affero General Public License Version 3
%  *    along with this program.  If not, see <https://www.gnu.org/licenses/>.
%  *
%  *    1. Redistributions of source code must retain the above copyright
%  *       notice, this list of conditions, and the following disclaimer.
%  *    2. Redistributions in binary form must reproduce the above copyright
%  *       notice, this list of conditions, and the following disclaimer in
%  *       the documentation and/or other materials provided with the
%  *       distribution.
%  *    3. No ownership or credit shall be claimed by anyone not mentioned in
%  *       the above copyright statement.
%  *    4. Any redistribution or public use of this software, in whole or in part,
%  *       whether standalone or as part of a different project, must remain
%  *       under the terms of the GNU Affero General Public License Version 3,
%  *       and all distributions in binary form must be accompanied by a copy of
%  *       the source code, as stated in the GNU Affero General Public License.
%  *
%  ****************************************************************************/

function A = get_A(T)
%get_A
%    A = get_A(T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    05-Feb-2024 11:01:36

t2 = 1.0./T;
t3 = t2.^2;
t4 = t2.^3;
t5 = t3.^2;
t6 = t3.*2.0;
t7 = t4.*6.0;
t8 = t5.*2.4e+1;
A = sparse([1,6,2,6,7,3,6,7,8,4,6,7,8,9,5,6,7,8,9,10,6,7,8,9,10,6,7,8,9,10,6,7,8,9,10,6,7,8,9,10,6,7,8,9,10],[1,1,2,2,2,3,3,3,3,4,4,4,4,4,5,5,5,5,5,5,6,6,6,6,6,7,7,7,7,7,8,8,8,8,8,9,9,9,9,9,10,10,10,10,10],[1.0,1.0,t2,1.0,t2,t6,1.0,t2.*2.0,t6,t7,1.0,t2.*3.0,t3.*6.0,t7,t8,1.0,t2.*4.0,t3.*1.2e+1,t4.*2.4e+1,t8,1.0,t2.*5.0,t3.*2.0e+1,t4.*6.0e+1,t5.*1.2e+2,1.0,t2.*6.0,t3.*3.0e+1,t4.*1.2e+2,t5.*3.6e+2,1.0,t2.*7.0,t3.*4.2e+1,t4.*2.1e+2,t5.*8.4e+2,1.0,t2.*8.0,t3.*5.6e+1,t4.*3.36e+2,t5.*1.68e+3,1.0,t2.*9.0,t3.*7.2e+1,t4.*5.04e+2,t5.*3.024e+3],10,10);
end